export enum StatusCarga {
  AGUARDANDO_DOCUMENTACAO = 'AGUARDANDO_DOCUMENTACAO',
  DOCUMENTACAO_VALIDADA = 'DOCUMENTACAO_VALIDADA',
  EM_INSPECAO = 'EM_INSPECAO',
  LIBERADA = 'LIBERADA',
  EM_MOVIMENTACAO = 'EM_MOVIMENTACAO',
  FINALIZADA = 'FINALIZADA',
  BLOQUEADA = 'BLOQUEADA',
  CANCELADA = 'CANCELADA',
}

export enum StatusValidacao {
  PENDENTE = 'PENDENTE',
  VALIDADO = 'VALIDADO',
  REJEITADO = 'REJEITADO',
}

export enum ResultadoInspecao {
  PENDENTE = 'PENDENTE',
  APROVADO = 'APROVADO',
  REPROVADO = 'REPROVADO',
}

export enum UnidadeMedida {
  TONELADAS = 'TONELADAS',
  QUILOGRAMAS = 'QUILOGRAMAS',
  LITROS = 'LITROS',
  METROS_CUBICOS = 'METROS_CUBICOS',
}

export enum StatusAreaArmazenamento {
  COM_ESPACO = 'COM_ESPACO',
  LOTADA = 'LOTADA',
}
